name: Build Pages

on:
  workflow_dispatch:
    inputs:
      folderName:
        description: 'Tex Folder to Build'
        required: true
        type: choice
        options:
        - 2024-01-18-talk
        - 2024-03-31-paper
      ignoreLock:
        description: 'Ignore flake.lock'
        required: false
        default: false
        type: boolean

jobs:
  buildPages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete Lockfile
        if: ${{ inputs.ignoreLock }}
        run: rm flake.lock
      - name: Build PDF
        run: |
          nix build .#packages.x86_64-linux.${{ inputs.folderName }}
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: result/*
          if-no-files-found: error
          retention-days: 1
          overwrite: true
